language: python
python:
    - "2.7"
    - "3.2"
install:
    - pip install pytest
    - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 -O `pwd`/../pypy.tar.bz2
    - tar -xf `pwd`/../pypy.tar.bz2 -C `pwd`/../
script: PYTHONPATH=$PYTONPATH:`python -c "from __future__ import print_function; import glob; import os; print(os.path.abspath(glob.glob('../pypy-pypy*')[0]))"` py.test
notifications:
    - email: false

